{
  log.debug("Received exception caught notice");
  listener.exceptionCaught(e);
}
