{
  replay(mockSocket);
  mc.setThrowIOExceptionOnFirstSocketCreate(true);
  try {
    mc.login();
    fail("No IOException thrown");
  }
 catch (  IOException e) {
  }
  assertEquals("createSocket not called 1 time",1,mc.createSocketCalls);
  assertEquals("createWriter not called 1 time",1,mc.createWriterCalls);
  assertEquals("createReader not called 1 time",1,mc.createReaderCalls);
  assertEquals("unexpected challenge action sent",0,mockWriter.challengeActionsSent);
  assertEquals("unexpected login action sent",0,mockWriter.loginActionsSent);
  assertEquals("unexpected other actions sent",0,mockWriter.otherActionsSent);
  assertEquals("unexpected call to setSocket()",0,mockReader.setSocketCalls);
  assertEquals("unexpected call to run()",0,mockReader.runCalls);
  assertEquals("unexpected call to die()",0,mockReader.dieCalls);
  verify(mockSocket);
}
